repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix]  # Automatically fix lint errors
      - id: ruff-format
